#  _   _       _   ____  _            _
# | | | | ___ | |_| __ )| | ___   ___| | __
# | |_| |/ _ \| __|  _ \| |/ _ \ / __| |/ /
# |  _  | (_) | |_| |_) | | (_) | (__|   <
# |_| |_|\___/ \__|____/|_|\___/ \___|_|\_\
#
# Funny minigame with PVP for PocketMine-MP
# (C) 2016 by SURVA.ml (https://github.com/SURVAml)
# Please post bugs on GitHub.
#

# In which world the game is
world: "HotBlock"

# How many players must be online that the block is active (prevent that one player is alone getting coins)
players: 4